import { useCallback, useState } from 'react'
import type { Node } from '@xyflow/react'
import type { Point, TaskPriority, TerminalNodeData, WorkspaceSpaceState } from '../../../types'
import { normalizeTaskTagSelection, sanitizeSpaces, toErrorMessage } from '../helpers'
import type { ContextMenuState, TaskCreatorState } from '../types'
import { expandSpaceToFitOwnedNodesAndPushAway } from '../../../utils/spaceAutoResize'

type SetNodes = (
  updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
  options?: { syncLayout?: boolean },
) => void

interface UseTaskCreatorParams {
  contextMenu: ContextMenuState | null
  setContextMenu: React.Dispatch<React.SetStateAction<ContextMenuState | null>>
  taskTagOptions: string[]
  nodesRef: React.MutableRefObject<Node<TerminalNodeData>[]>
  setNodes: SetNodes
  spacesRef: React.MutableRefObject<WorkspaceSpaceState[]>
  onSpacesChange: (spaces: WorkspaceSpaceState[]) => void
  onRequestPersistFlush?: () => void
  suggestTaskTitle: (
    requirement: string,
  ) => Promise<{ title: string; priority: TaskPriority; tags: string[] }>
  createTaskNode: (
    anchor: Point,
    title: string,
    requirement: string,
    autoGeneratedTitle: boolean,
    priority: TaskPriority,
    tags: string[],
  ) => Node<TerminalNodeData> | null
}

export function useWorkspaceCanvasTaskCreator({
  contextMenu,
  setContextMenu,
  taskTagOptions,
  nodesRef,
  setNodes,
  spacesRef,
  onSpacesChange,
  onRequestPersistFlush,
  suggestTaskTitle,
  createTaskNode,
}: UseTaskCreatorParams): {
  taskCreator: TaskCreatorState | null
  setTaskCreator: React.Dispatch<React.SetStateAction<TaskCreatorState | null>>
  openTaskCreator: () => void
  closeTaskCreator: () => void
  generateTaskTitle: () => Promise<void>
  createTask: () => Promise<void>
} {
  const [taskCreator, setTaskCreator] = useState<TaskCreatorState | null>(null)

  const openTaskCreator = useCallback(() => {
    if (!contextMenu || contextMenu.kind !== 'pane') {
      return
    }

    setTaskCreator({
      anchor: {
        x: contextMenu.flowX,
        y: contextMenu.flowY,
      },
      title: '',
      requirement: '',
      priority: 'medium',
      selectedTags: [],
      autoGenerateTitle: true,
      isGeneratingTitle: false,
      isCreating: false,
      error: null,
    })

    setContextMenu(null)
  }, [contextMenu, setContextMenu])

  const closeTaskCreator = useCallback(() => {
    setTaskCreator(prev => {
      if (!prev || prev.isCreating || prev.isGeneratingTitle) {
        return prev
      }

      return null
    })
  }, [])

  const generateTaskTitle = useCallback(async () => {
    if (!taskCreator) {
      return
    }

    const requirement = taskCreator.requirement.trim()
    if (requirement.length === 0) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              error: '任务要求不能为空。',
            }
          : prev,
      )
      return
    }

    setTaskCreator(prev =>
      prev
        ? {
            ...prev,
            isGeneratingTitle: true,
            error: null,
          }
        : prev,
    )

    try {
      const suggestion = await suggestTaskTitle(requirement)
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              title: suggestion.title,
              priority: suggestion.priority,
              selectedTags: suggestion.tags,
              isGeneratingTitle: false,
              error: null,
            }
          : prev,
      )
    } catch (error) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              isGeneratingTitle: false,
              error: `自动生成失败：${toErrorMessage(error)}`,
            }
          : prev,
      )
    }
  }, [suggestTaskTitle, taskCreator])

  const createTask = useCallback(async () => {
    if (!taskCreator) {
      return
    }

    const requirement = taskCreator.requirement.trim()
    let title = taskCreator.title.trim()
    let priority = taskCreator.priority
    let selectedTags = normalizeTaskTagSelection(taskCreator.selectedTags, taskTagOptions)

    if (requirement.length === 0) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              error: '任务要求不能为空。',
            }
          : prev,
      )
      return
    }

    setTaskCreator(prev =>
      prev
        ? {
            ...prev,
            isCreating: true,
            error: null,
          }
        : prev,
    )

    let autoGeneratedTitle = false

    try {
      if (title.length === 0) {
        if (!taskCreator.autoGenerateTitle) {
          setTaskCreator(prev =>
            prev
              ? {
                  ...prev,
                  isCreating: false,
                  error: '请输入任务名称或开启自动生成。',
                }
              : prev,
          )
          return
        }

        const suggestion = await suggestTaskTitle(requirement)
        title = suggestion.title
        priority = suggestion.priority
        selectedTags = suggestion.tags
        autoGeneratedTitle = true
      }

      const created = createTaskNode(
        taskCreator.anchor,
        title,
        requirement,
        autoGeneratedTitle,
        priority,
        selectedTags,
      )

      if (!created) {
        setTaskCreator(prev =>
          prev
            ? {
                ...prev,
                isCreating: false,
                error: '任务节点无法放置，请先整理画布后重试。',
              }
            : prev,
        )
        return
      }

      const targetSpace =
        spacesRef.current.find(space => {
          if (!space.rect) {
            return false
          }

          return (
            taskCreator.anchor.x >= space.rect.x &&
            taskCreator.anchor.x <= space.rect.x + space.rect.width &&
            taskCreator.anchor.y >= space.rect.y &&
            taskCreator.anchor.y <= space.rect.y + space.rect.height
          )
        }) ?? null

      if (targetSpace) {
        const nextSpaces = sanitizeSpaces(
          spacesRef.current.map(space => {
            const filtered = space.nodeIds.filter(nodeId => nodeId !== created.id)

            if (space.id !== targetSpace.id) {
              return { ...space, nodeIds: filtered }
            }

            return { ...space, nodeIds: [...new Set([...filtered, created.id])] }
          }),
        )

        const { spaces: pushedSpaces, nodePositionById } = expandSpaceToFitOwnedNodesAndPushAway({
          targetSpaceId: targetSpace.id,
          spaces: nextSpaces,
          nodeRects: nodesRef.current.map(node => ({
            id: node.id,
            rect: {
              x: node.position.x,
              y: node.position.y,
              width: node.data.width,
              height: node.data.height,
            },
          })),
          gap: 24,
        })

        if (nodePositionById.size > 0) {
          setNodes(
            prevNodes => {
              let hasChanged = false
              const next = prevNodes.map(node => {
                const nextPosition = nodePositionById.get(node.id)
                if (!nextPosition) {
                  return node
                }

                if (node.position.x === nextPosition.x && node.position.y === nextPosition.y) {
                  return node
                }

                hasChanged = true
                return {
                  ...node,
                  position: nextPosition,
                }
              })

              return hasChanged ? next : prevNodes
            },
            { syncLayout: false },
          )
        }

        onSpacesChange(pushedSpaces)
        onRequestPersistFlush?.()
      }

      setTaskCreator(null)
    } catch (error) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              isCreating: false,
              error: `创建任务失败：${toErrorMessage(error)}`,
            }
          : prev,
      )
    }
  }, [
    createTaskNode,
    nodesRef,
    onRequestPersistFlush,
    onSpacesChange,
    setNodes,
    spacesRef,
    suggestTaskTitle,
    taskCreator,
    taskTagOptions,
  ])

  return {
    taskCreator,
    setTaskCreator,
    openTaskCreator,
    closeTaskCreator,
    generateTaskTitle,
    createTask,
  }
}
